% Clase para los bloques de satélites

classdef SateliteBlock
	enumeration
		UNKNOWN_BLOCK, ...
		GPS_BLOCK_I, ...
		GPS_BLOCK_II, ...
		GPS_BLOCK_IIA, ...
		GPS_BLOCK_IIR, ...
		GPS_BLOCK_IIR_M, ...
		GPS_BLOCK_IIF, ...
		GPS_BLOCK_IIIA, ...
		GLONASS, ...
		GLONASS_M, ...
		GLONASS_K1, ...
		GLONASS_K2, ...
		GALILEO_IOV, ...
		GALILEO_FOC, ...
		BEIDOU_2_GEO, ...
		BEIDOU_2_IGSO, ...
		BEIDOU_2_MEO, ...
		BEIDOU_3_IGSO, ...
		BEIDOU_3_MEO, ...
		BEIDOU_3_GEO, ...
		IRNSS_1_GEO, ...
		IRNSS_1_IGSO, ...
		QZSS_BLOCK_I, ...
		QZSS_BLOCK_II_IGSO, ...
		QZSS_BLOCK_II_GEO
   end
end